### ISSUE TITLE
Getting tika response error no attribute 

### ISSUE THREAD

**Issue by Tonynks** [stumpylog/tika-client#2]
When trying to import old xls file in paperlessngx using tika as a parser, I get an error stating no attribute found and it will not convert.  
I'm running the latest docker image for 
Paperlessngx
Gotenberg
Apache/tika

Thanks for help..
If u need any other info please ask.  
-tony-

**Comment by abendorg** [comment]
I am currently running into the same issue in paperlessngx with pptx as well as xls (xlsx/docx work fine). "'TikaResponse' object has no attribute 'created'" error on both file types.

**Comment by Tonynks** [comment]
`[2023-06-25 06:34:27,692] [WARNING] [tika-client.utils] Under-specified content-type: application/vnd.ms-excel
06/24/2023 10:34:28 PM
[2023-06-25 06:34:28,205] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[b590748b-f7bd-4542-b816-823759cc0e33] raised unexpected: AttributeError("'TikaResponse' object has no attribute 'created'")
06/24/2023 10:34:28 PM
Traceback (most recent call last):
06/24/2023 10:34:28 PM
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 477, in trace_task
06/24/2023 10:34:28 PM
    R = retval = fun(*args, **kwargs)
06/24/2023 10:34:28 PM
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 760, in __protected_call__
06/24/2023 10:34:28 PM
    return self.run(*args, **kwargs)
06/24/2023 10:34:28 PM
  File "/usr/src/paperless/src/documents/tasks.py", line 133, in consume_file
06/24/2023 10:34:28 PM
    document = Consumer().try_consume_file(
06/24/2023 10:34:28 PM
  File "/usr/src/paperless/src/documents/consumer.py", line 382, in try_consume_file
06/24/2023 10:34:28 PM
    document_parser.parse(self.path, mime_type, self.filename)
06/24/2023 10:34:28 PM
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 70, in parse
06/24/2023 10:34:28 PM
    self.date = parsed.created
06/24/2023 10:34:28 PM
AttributeError: 'TikaResponse' object has no attribute 'created'
`

**Comment by stumpylog** [comment]
Thanks, I'll check into both file types.  Tika is tricky, as the responses aren't really documented anywhere.  Should be pretty quick though once I have some time

**Comment by Tonynks** [comment]
Thank you so much.  Keep me posted!

**Comment by stumpylog** [comment]
A new release is published and will be in paperless soon.
